### PR TITLE
facebook fix + configurable storage/cookie archiving

### LINKED ISSUE #272: [Bug]: web-recorder can not detect facebook video
### ArchiveWeb.page Version

v0.13.2

### What did you expect to happen? What happened instead?

web-recorder is unable to detect facebook videos since a week, it seems that facebook has made some changes to their data model.

### Step-by-step reproduction instructions

i was trying to archive facebook video post using the chrome extension

https://www.facebook.com/watch?v=1259613418712038

Screenshot 2024-11-12 at 15 20 18

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by ikreymer**
support for configurable cookie / storage archiving, from UI settings from #276
fix for facebook archiving + replay using dash rewriting + range-from-query replay via wabac.js 2.20.4
fixes #272, #273

### CODE REVIEW

**Comment by tw4l** [comment]
The settings in the Preferences tab don't seem to actually save/stick, so I'm unable to test this.

Steps to reproduce:
1. Build local AWP
2. Add as extension to browser (I tested Chrome and Brave) via "Load unpacked" on `chrome://extensions`
3. Open extension preferences, attempt to modify cookie and local storage settings and press Save
4. Open extension preferences again, verify saved choices didn't persist

File: src/ui/app.ts [hunk 1]
```diff
@@ -91,20 +95,27 @@ class ArchiveWebApp extends ReplayWebApp {
...
+
+  async initOpts() {
+    this.autorun = (await getLocalOption("autorunBehaviors") === "1");
+
+    const archiveCookies = await getLocalOption("archiveCookies");
+    // default to true if unset to match existing behavior
+    if (archiveCookies === null) {
+      await setLocalOption("archiveCookies", "1");
+      this.archiveCookies = true;
+    }
```
Comment (tw4l) [inline src/ui/app.ts:116]: Might need to add another `if` statement here to set this.archiveCookies to true if `archiveCookies === "1"`?

**Review by tw4l — APPROVED** [review]
Nice, after those changes to make the settings persist, this is working well! Verified that Facebook photos and videos are now fixed, and that Bluesky logged-in replay works if archiving local storage is enabled.

Nice work!
